<?php
/**
 * @var Dev101\UniversalWidget\Block\Widget\Product\ProductList $block
 */
$getConditions1Tab = 'conditions_encoded';
$collection=$block->getProductsInTab($getConditions1Tab);

?>

<?php foreach ($collection as $product): ?>
    <div class="block-title">
        <strong><?= $block->escapeHtml(__($product->getTitle())) ?></strong>
    </div>
<?php endforeach; ?>
<?php
    $getConditions2Tab = 'Conditions2Tab';
    $getConditions3Tab = 'Conditions3Tab';
    $productCollection = $this->getProductsInTab($getConditions1Tab);
    $productCollection2 = $this->getProductsInTab($getConditions2Tab);
    $productCollection3 = $this->getProductsInTab($getConditions3Tab);
    $productCount = $this->getData('productcount');
    $imageWidth = $this->getData('imagewidth');
    $imageheight = $this->getData('imageheight');
    $mode = 'grid';
    $title = $block->escapeHtml(__($block->getData('title')));
    $title2 = $block->escapeHtml(__($block->getData('title2')));
    $title3 = $block->escapeHtml(__($block->getData('title3')));
    $type = 'widget-featured-grid';
    $image = 'featured_products_content_widget_grid';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

?>


    <div class="product data items"
         data-mage-init='{"mage/tabs": {"openedState": "active", "animate": {"duration": 100}, "active": 0}}'>
        <div class="item title" data-role="collapsible" aria-selected="true" aria-expanded="true">
            <a class="switch" data-toggle="trigger" href="#tab-cars">
                <div class="block-title">
                    <strong role="heading" aria-level="2"><?php /* @escapeNotVerified */
                        echo $title; ?></strong>
                </div>
            </a>
        </div>
        <div id="tab-cars" class="item content" data-role="content">
            <div class="block widget block-universal-products <?php /* @escapeNotVerified */
            echo $mode; ?>">
                <div class="block-content">
                    <?php /* @escapeNotVerified */
                    echo '<!-- ' . $image . '-->' ?>
                    <div class="products-<?php /* @escapeNotVerified */
                    echo $mode; ?> <?php /* @escapeNotVerified */
                    echo $mode; ?>">
                        <ol class="product-items <?php /* @escapeNotVerified */
                        echo $type; ?>">
                            <?php
                            $iterator = 1; ?>
                            <?php
                            foreach ($productCollection as $_product): ?>


                                <?php /* @escapeNotVerified */
                                echo ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                                <div class="product-item-info">
                                    <?php
                                    $image_url = $block->imageHelperObj()->init($_product, 'product_page_image_small')->setImageFile($_product->getFile())->resize($imageWidth, $imageheight)->getUrl();
                                    ?>
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" class="product-item-photo">
                                        <img src="<?php
                                        echo $image_url; ?>" alt="<?php
                                        echo $this->escapeHtml($_product->getName()) ?>" />
                                    </a>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?php
                                            echo $block->escapeHtml($_product->getName()) ?>"
                                               href="<?php /* @escapeNotVerified */
                                               echo $_product->getProductUrl() ?>"
                                               class="product-item-link">
                                                <?php
                                                echo $block->escapeHtml($_product->getName()) ?>
                                            </a>
                                        </strong>
                                        <?php if ($templateType) : ?>
                                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                        <?php endif; ?>
                                        <?php
                                        echo $this->getProductPriceHtml($_product, $type);
                                        ?>

                                        <div class="product-item-actions">

                                            <div class="actions-primary">
                                                <?php
                                                if ($_product->isSaleable()): ?>
                                                    <?php
                                                    if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */
                                                                echo $block->getAddToCartUrl($_product) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */
                                                        echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php
                                                    else: ?>
                                                        <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getId() ]);
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?php /* @escapeNotVerified */
                                                                echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */
                                                        echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php
                                                    endif; ?>
                                                <?php
                                                else: ?>
                                                    <?php
                                                    if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */
                                                                echo __('In stock') ?></span></div>
                                                    <?php
                                                    else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                                echo __('Out of stock') ?></span></div>
                                                    <?php
                                                    endif; ?>
                                                <?php
                                                endif; ?>
                                            </div>


                                        </div>

                                    </div>
                                </div>
                                <?php
                                echo ($iterator == count($productCollection) + 1) ? '</li>' : '' ?>
                            <?php
                            endforeach ?>
                        </ol>
                    </div>
                   <div id="pager1"><?= $block->getPagersHtml($getConditions1Tab) ?></div>
                </div>
            </div>
        </div>

        <div class="item title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#tab-movies">
                <div class="block-title">
                    <strong role="heading" aria-level="2"><?php /* @escapeNotVerified */
                        echo $title2; ?></strong>
                </div>
            </a>
        </div>
        <div id="tab-movies" class="item content" data-role="content">
            <div class="block widget block-universal-products <?php /* @escapeNotVerified */
            echo $mode; ?>">
                <div class="block-content">
                    <?php /* @escapeNotVerified */
                    echo '<!-- ' . $image . '-->' ?>
                    <div class="products-<?php /* @escapeNotVerified */
                    echo $mode; ?> <?php /* @escapeNotVerified */
                    echo $mode; ?>">
                        <ol class="product-items <?php /* @escapeNotVerified */
                        echo $type; ?>">
                            <?php
                            $iterator = 1; ?>
                            <?php
                            foreach ($productCollection2 as $_product): ?>

                                <?php /* @escapeNotVerified */
                                echo ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                                <div class="product-item-info">
                                    <?php
                                    $image_url = $block->imageHelperObj()->init($_product, 'product_page_image_small')->setImageFile($_product->getFile())->resize($imageWidth, $imageheight)->getUrl();
                                    ?>
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" class="product-item-photo">
                                        <img src="<?php
                                        echo $image_url; ?>" alt="<?php
                                        echo $this->escapeHtml($_product->getName()) ?>" />
                                    </a>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?php
                                            echo $block->escapeHtml($_product->getName()) ?>"
                                               href="<?php /* @escapeNotVerified */
                                               echo $_product->getProductUrl() ?>"
                                               class="product-item-link">
                                                <?php
                                                echo $block->escapeHtml($_product->getName()) ?>
                                            </a>
                                        </strong>
                                        <?php if ($templateType) : ?>
                                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                        <?php endif; ?>
                                        <?php
                                        echo $this->getProductPriceHtml($_product, $type);
                                        ?>

                                        <div class="product-item-actions">

                                            <div class="actions-primary">
                                                <?php
                                                if ($_product->isSaleable()): ?>
                                                    <?php
                                                    if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */
                                                                echo $block->getAddToCartUrl($_product) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */
                                                        echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php
                                                    else: ?>
                                                        <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getId() ]);
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?php /* @escapeNotVerified */
                                                                echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */
                                                        echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php
                                                    endif; ?>
                                                <?php
                                                else: ?>
                                                    <?php
                                                    if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */
                                                                echo __('In stock') ?></span></div>
                                                    <?php
                                                    else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                                echo __('Out of stock') ?></span></div>
                                                    <?php
                                                    endif; ?>
                                                <?php
                                                endif; ?>
                                            </div>


                                        </div>

                                    </div>
                                </div>
                                <?php
                                echo ($iterator == count($productCollection2) + 1) ? '</li>' : '' ?>
                            <?php
                            endforeach ?>
                        </ol>
                    </div>
                    <div id="pager2"><?= $block->getPagersHtml($getConditions2Tab) ?></div>
                </div>
            </div>

        </div>

        <div class="item title" data-role="collapsible">
            <a class="switch" data-toggle="trigger" href="#tab-music">
                <strong>
                    <div class="block-title">
                        <strong role="heading" aria-level="2"><?php echo $title3; ?> </strong>
                    </div>
                </strong>
            </a>
        </div>
        <div id="tab-music" class="item content" data-role="content">
            <div class="block widget block-universal-products <?php /* @escapeNotVerified */
            echo $mode; ?>">
                <div class="block-content">
                    <?php /* @escapeNotVerified */
                    echo '<!-- ' . $image . '-->' ?>
                    <div class="products-<?php /* @escapeNotVerified */
                    echo $mode; ?> <?php /* @escapeNotVerified */
                    echo $mode; ?>">
                        <ol class="product-items <?php /* @escapeNotVerified */
                        echo $type; ?>">
                            <?php
                            $iterator = 1; ?>
                            <?php
                            foreach ($productCollection3 as $_product): ?>


                                <?php /* @escapeNotVerified */
                                echo ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                                <div class="product-item-info">
                                    <?php
                                    $image_url = $block->imageHelperObj()->init($_product, 'product_page_image_small')->setImageFile($_product->getFile())->resize($imageWidth, $imageheight)->getUrl();
                                    ?>
                                    <a href="<?php /* @escapeNotVerified */
                                    echo $_product->getProductUrl() ?>" class="product-item-photo">
                                        <img src="<?php
                                        echo $image_url; ?>" alt="<?php
                                        echo $this->escapeHtml($_product->getName()) ?>" />
                                    </a>
                                    <div class="product-item-details">
                                        <strong class="product-item-name">
                                            <a title="<?php
                                            echo $block->escapeHtml($_product->getName()) ?>"
                                               href="<?php /* @escapeNotVerified */
                                               echo $_product->getProductUrl() ?>"
                                               class="product-item-link">
                                                <?php
                                                echo $block->escapeHtml($_product->getName()) ?>
                                            </a>
                                        </strong>
                                        <?php if ($templateType) : ?>
                                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                        <?php endif; ?>
                                        <?php
                                        echo $this->getProductPriceHtml($_product, $type);
                                        ?>

                                        <div class="product-item-actions">

                                            <div class="actions-primary">
                                                <?php
                                                if ($_product->isSaleable()): ?>
                                                    <?php
                                                    if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */
                                                                echo $block->getAddToCartUrl($_product) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */
                                                        echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php
                                                    else: ?>
                                                        <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getId() ]);
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?php /* @escapeNotVerified */
                                                                echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */
                                                        echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */
                                                                echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php
                                                    endif; ?>
                                                <?php
                                                else: ?>
                                                    <?php
                                                    if ($_product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */
                                                                echo __('In stock') ?></span></div>
                                                    <?php
                                                    else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */
                                                                echo __('Out of stock') ?></span></div>
                                                    <?php
                                                    endif; ?>
                                                <?php
                                                endif; ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <?php
                                echo ($iterator == count($productCollection3) + 1) ? '</li>' : '' ?>
                            <?php
                            endforeach ?>
                        </ol>
                    </div>
                    <div id="pager3"><?= $block->getPagersHtml($getConditions3Tab) ?></div>
                </div>
            </div>
        </div>
    </div>

        <script type="text/javascript">
            require([
                'jquery',
                'mage/tabs'
            ], function($){
                $(function () {
                    $("#Tab1").tabs();
                });
            });
        </script>

