<?php
/**
 * @var \Roadmap\CustomizeCheckoutStep\Block\Adminhtml\CustomerComment $block
 */
$customerComment = $block->getCustomerComment();
?>
<?php if (isset($customerComment)):?>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-simple-note">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__("Customer's comment")) ?></span>
            </div>
            <div class="admin__page-section-item-content"><?= $customerComment ?></div>
        </div>
    </div>
<?php endif;?>

