<button data-role="closeBtn" id="rule_button-save-submit-<?= /* @noEscape */
/**@var $block \Dev101\UniversalWidget\Block\Widget\Options\ChooseButtonTemplateHandler */
$block->getData('cuttedName') ?>" type="button">
    <?= __('Save') ?>
</button>
<script>

    require(['jquery', 'Magento_Ui/js/modal/modal', 'Dev101_UniversalWidget/js/prepareDataCondition'], function (jQuery, modal, prepareDataCondition) {

        prepareDataCondition.prepareCondition("<?= /* @noEscape */ $block->getData('cuttedName')?>",
            "<?= /* @noEscape */ $block->getData('name')?>",
            "<?= /* @noEscape */ $this->getUrl("universal/conditions_rule/preparedata")?>");

    });
</script>
