<?php
/**
 * @var \Kozar\Prices\Block\Index $block
 */
$allows_arr = $block->getAllows();
if ($allows_arr[0]) {
    $arr = $block->testVersion();
    if (count($arr) > 5) {
        $name = $arr[5];
    }
    if (isset($name)) {
        ?>
        <p>Final price for Sku <?php echo $name . " : " . $arr[1]; ?></p>
        <p>Final price for other products: <?=$arr[6]?></p>
        <?php
    } else {
        if ($allows_arr[2]) {
            ?>
            <p>Final price: <?=$arr[1]?></p>
            <?php
        } ?>
        <?php
    }
    if ($allows_arr[1]) { ?>
        <p>Base price: <?=$arr[0]?></p>
    <?php }
    if ($allows_arr[3]) {
        ?>
        <p>Special price: <?=$arr[2]?></p>
        <?php
    }
    if ($allows_arr[4]) {?>
    <p>Tier price: <?=$arr[3]?></p>
    <?php }
    if ($allows_arr[5]) {
        ?>
        <p>Catalog rule price: <?=$arr[4]?></p>
        <?php
    }
}
?>
